inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

inherit_from:
  - .rubocop_rspec.yml

plugins: rubocop-on-rbs

RBS:
  Enabled: true

AllCops:
  Exclude:
    - 'lib/oauth/helper.rb'

Layout/IndentationConsistency:
  Exclude: ['*.md']
